version: "3.8"

services:
  collabzone:
    build: .
    container_name: collabzone
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.collabzone.rule=Host(`collabzone.betaclicdigitale.com`)"
      - "traefik.http.services.collabzone.loadbalancer.server.port=5000"
      - "traefik.http.routers.collabzone.entrypoints=web"
    volumes:
      - ./static/uploads:/app/static/uploads
    networks:
      - traefik

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8081:8080
    volumes:
      - ./static/uploads:/var/www/html
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.adminer.rule=Host(`adminer.betaclicdigitale.com`)"
      - "traefik.http.services.adminer.loadbalancer.server.port=8080"
      - "traefik.http.routers.adminer.entrypoints=web"

networks:
  traefik:
    external: true
