version: "3.8"

services:
  collabzone:
    build: .
    container_name: collabzone
    restart: unless-stopped
    ports:
      - "5001:5000"
    volumes:
      - ./static/uploads:/app/static/uploads
