version: "3.8"
services:
  collabzone:
    build: .
    container_name: collabzone
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.collabzone.rule=Host(`collabzone.betaclicdigitale.com`)"
      - "traefik.http.services.collabzone.loadbalancer.server.port=5000"
      - "traefik.http.routers.collabzone.entrypoints=web"
    # Tu peux commenter ports: sauf si accès direct (hors traefik) souhaité
    ports:
      - "5001:5000"
    volumes:
      - ./static/uploads:/app/static/uploads
