version: "3.8"

services:
  collabzone:
    build: .
    container_name: collabzone
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.collabzone.rule=Host(`collabzone.betaclicdigitale.com`)"
      - "traefik.http.services.collabzone.loadbalancer.server.port=5000"
      - "traefik.http.routers.collabzone.entrypoints=web"
    networks:
      - traefik
    volumes:
      - ./static/uploads:/app/static/uploads
    # Garde le port 5001:5000 SEULEMENT si tu veux accéder directement à l’app sans Traefik
    ports:
      - "5001:5000"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    networks:
      - traefik
    # Optionnel : monte le dossier contenant tes .db pour y accéder via Adminer si besoin
    volumes:
      - ./static/uploads:/app/static/uploads

networks:
  traefik:
    external: true
